language: node_js
node_js:
- node
env:
  global:
    - "TOKEN_LIST=f8290ed2-9332-49f4-861f-4791a787f026"
    - secure: jDDXO1ZAhahvGX7TQGlc9dLbDyI6cOkUfdaOZh36mLzivVxokB32+U4sSA78IXZhafAONqwU18BjgBlxVxhXk1cUON6kjV+lYe4dNICHtuZ495miqCuIo7j7V0+A8eltn9dAPITEprjAC4g9yHQrCPIrnqy+Mo4c8c6ownPOzNRAtt2JL7pGIkZw67SyCTNWHtgfRv7bLj2vv47f9kUgIgp2c0qAKN6S7WgdpufHYOjBZEUE3u/mERBBrMb74kvqG326obaZxckqZjGvlQAu+xuaHKbl87+yU4xIqCYtLiqWrxwaSDOT+pgRkFaqSK8O9Bwik18nsPtYeX/gz0KUdMHHZMu8ktfu+xchSUtUS9nasam/kTaeHrYOmtfNG69c0JuyQMT1okDbW01DrxcPcJ+SN1mSnH8EFiP/DL1GNRPubjZldYHszL1/tMyYeWtK5F198NYlX2h3sNdgiPtyoJFSSYa0OE4g29tdHJfTtrHPOWBVVFCS27ixfYYdqU9b5Fz9E55dq1sigftL5sXLlD3EED3oC34lwm+WT/5Lk0aVoWwkRqWYnUl1ER68AZxHKfFsmq8FRn/PMt+QyZbctH077X3kVO/iTYMB09yuZggSwlL+XyfrafMNgTuIr3eL6G5ULJORwY1IB6HU5CM+4goLs6LWJC0Dl8CEe7lJ3CY=
