version: "2.1"

services:
  ratios:
    image: ratios
    build: .
    restart: always
    environment:
      - "DATABASE_URL=postgres://ratios:password@ratios-postgres/ratios"
      - "EARLIEST_BACKFILL=2018-12-31"
      - "LATEST_BACKFILL=2019-01-04"
      - CURRENCY_OXR_API_ID
      - CURRENCY_UPHOLD_KEY
      - CURRENCY_UPHOLD_SECRET
      - DEBUG
      - DEBUG_COLORS
      - HEROKU_SLUG_COMMIT
      - NODE_ENV
      - PORT
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - SENTRY_DSN
