version: "2.1"

networks:
  ratios:
    driver: bridge

services:
  ratios-postgres:
    container_name: ratios-postgres
    image: postgres:10.4
    ports:
      - "4010:5432"
    networks:
      - ratios
    environment:
      - "POSTGRES_USER=ratios"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=ratios"

  ratios-web:
    container_name: ratios-web
    command: "npm start"
    ports:
      - "4000:8080"
    networks:
      - ratios
    extends:
      file: base.yml
      service: ratios
    depends_on:
      - ratios-postgres
    environment:
      - "PORT=8080"
    volumes:
      - ./:/usr/src/app

  ratios-history:
    container_name: ratios-history
    command: "npm run history"
    networks:
      - ratios
    extends:
      file: base.yml
      service: ratios
    depends_on:
      - ratios-postgres
    volumes:
      - ./:/usr/src/app

  ratios-migrate:
    container_name: ratios-migrate
    command: "npm run migrate-up"
    networks:
      - ratios
    extends:
      file: base.yml
      service: ratios
    depends_on:
      - ratios-postgres
    volumes:
      - ./:/usr/src/app
