import http from './server.test'
import grpc from './grpc.test'
import tests from './abstracted'

const httpTests = tests('http', http)
httpTests.allRates()
httpTests.allRatesFilters()
httpTests.allRatesFiltersUnknown()
httpTests.bearerHeader()
httpTests.bearerHeaderError()
httpTests.cachesCorrectly()
httpTests.canRefresh()
httpTests.checkAvailableCurrencies()
httpTests.isUp()
httpTests.getKey()
httpTests.legacyRates()
httpTests.metrics()
httpTests.relativeHistory()
httpTests.retrievePreviousDays()
httpTests.retrievePreviousDaysSingle()
httpTests.retrievesCSV()
httpTests.retrievesCSVRelative()
httpTests.singularRates()

const grpcTests = tests('grpc', grpc)
grpcTests.allRates()
grpcTests.allRatesFilters()
grpcTests.allRatesFiltersUnknown()
// grpcTests.bearerHeader()
// grpcTests.bearerHeaderError()
grpcTests.cachesCorrectly()
grpcTests.canRefresh()
grpcTests.checkAvailableCurrencies()
grpcTests.isUp()
grpcTests.getKey()
grpcTests.legacyRates()
// grpcTests.metrics()
grpcTests.relativeHistory()
grpcTests.retrievePreviousDays()
grpcTests.retrievePreviousDaysSingle()
// grpcTests.retrievesCSV()
// grpcTests.retrievesCSVRelative()
grpcTests.singularRates()
